Update version info endpoint
openfaas/faas pull request #1616
Opened 2021-01-18 04:02 UTC by viveksyngh

This commits updates version endpoint to use ProviderInfo and VersionInfo structs from
faas-provider.GatewayInfo now uses ProviderInfo and VersionInfo structs. GatewayInfo is
left within gateway. Consumer of this endpoint should use typed struct GatewayInfo to
parse response.

## Description

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-19 08:25 UTC, alexellis commented
@LucasRoesler can you suggest a way to have the best of both here? No error in older versions of the CLI, and the new typed struct elsewhere? AFAIK the schema hasn't changed

2021-01-19 14:57 UTC, LucasRoesler commented
@alexellis unfortunately, there is no good answer here.  Either the new api schema needs to include the previous fields (and the server needs to populate them) _or_ we need a new api version and we need to sever both v1 and v2 endpoints for some amount of time. 

The new data, moving it to new field names seems very undesirable. Adding a new endpoint and deprecating the old one is probably the simplest but has its own problem, what if the new CLI points at an old server? The CLI should know how to fallback to the original API if the new API is not found.  Basically a variation of API negotiation like the docker CLI does

2021-01-20 12:03 UTC, alexellis commented on gateway/handlers/infohandler.go
> -				Orchestration: provider["orchestration"].(string),
@viveksyngh why are we no longer setting orchestration here?

2021-01-20 12:07 UTC, alexellis commented
Sorry for causing confusion here - the schema didn't change, it was another error we were bumping into caused by an empty string in gateways built during development.

https://github.com/openfaas/faas/commit/2e2250afe843e94fcc34e85c5c5173c8602ca56c

OK to merge.

2021-01-20 12:07 UTC, alexellis approved these changes
LGTM

2021-01-20 12:07 UTC, alexellis approved these changes
LGTM

2021-01-20 12:08 UTC, alexellis commented
@viveksyngh Doesn't the gateway use go mod now?

2021-01-20 12:11 UTC, viveksyngh commented
No it does not .. I think we should migrate it to use go mod

2021-01-21 19:22 UTC, alexellis commented
Your wish is my command. #1617 

Want to rebase?

2021-01-21 19:22 UTC, alexellis requested changes
Rebase required and go mod instead of dep (the original PR was fine, but I migrated us to modules between then and now)

2021-01-23 11:26 UTC, viveksyngh commented
@alexellis  Rebased it.

2021-01-30 14:53 UTC, alexellis approved these changes
Approved

2021-01-30 14:53 UTC, merged